/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Arm(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/arm.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(()=>{
    console.log(actions);
    console.log(materials)
    console.log(nodes);
    actions.arm.play();

  }, [])


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={10}>
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/arm.glb')
